export interface Establishment {
  id: number;
  slug: string;
  name: string;
  description: string;
  address: string;
  phone: string;
  whatsapp: string;
  website: string;
  category_name?: string;
  category_slug?: string;
  destination_name?: string;
  destination_slug?: string;
  primary_image?: string;
  rating_avg: number;
  review_count: number;
  price_level: string;
  is_featured: boolean;
  services: string;
  membership_tier: string;
  has_hdv_seal?: boolean;
}

export const ESTABLISHMENTS_MOCK: Establishment[] = [
  // HOTELES
  {
    id: 1,
    slug: "hotel-tamanaco-intercontinental",
    name: "Hotel Tamanaco InterContinental",
    description: "Un oasis urbano en el corazón de Caracas, con hermosas vistas al cerro El Ávila, amplias piscinas templadas y restaurantes gourmet de clase mundial.",
    address: "Avenida Principal de Las Mercedes, Caracas, Miranda",
    phone: "+58 212 9097111",
    whatsapp: "+58 414 1234567",
    website: "https://www.ihg.com",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Caracas",
    destination_slug: "caracas",
    primary_image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    rating_avg: 4.8,
    review_count: 324,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\", \"spa\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 3,
    slug: "hotel-hesperia-margarita",
    name: "Hotel Hesperia Isla Margarita",
    description: "Complejo vacacional de 5 estrellas frente a la playa con campo de golf de 18 hoyos, múltiples piscinas y acceso directo a Playa Zaragoza.",
    address: "Valle de Pedro González, Isla de Margarita, Nueva Esparta",
    phone: "+58 295 4007100",
    whatsapp: "+58 412 5556677",
    website: "https://www.hesperia.com",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Isla de Margarita",
    destination_slug: "margarita",
    primary_image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop",
    rating_avg: 4.6,
    review_count: 567,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\"]",
    membership_tier: "oro",
    has_hdv_seal: false
  },
  {
    id: 7,
    slug: "hotel-cayena-caracas",
    name: "Hotel Cayena Caracas",
    description: "Exclusivo hotel boutique de ultra-lujo en La Castellana. Combina el encanto colonial con comodidades modernas y vistas espectaculares del Ávila.",
    address: "Avenida Don Eugenio Mendoza, La Castellana, Caracas",
    phone: "+58 212 2743600",
    whatsapp: "+58 424 1112233",
    website: "https://hotelcayena.com",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Caracas",
    destination_slug: "caracas",
    primary_image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    rating_avg: 4.9,
    review_count: 145,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 8,
    slug: "hotel-eurobuilding-caracas",
    name: "Eurobuilding Hotel & Suites",
    description: "Un ícono de la hospitalidad cinco estrellas en Caracas. Ideal para viajes de negocios o placer, con centro de convenciones y gastronomía gourmet.",
    address: "Calle La Guairita, Chuao, Caracas, Miranda",
    phone: "+58 212 9021111",
    whatsapp: "+58 414 7778899",
    website: "https://www.hoteleuro.com",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Caracas",
    destination_slug: "caracas",
    primary_image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
    rating_avg: 4.7,
    review_count: 412,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\", \"spa\"]",
    membership_tier: "oro",
    has_hdv_seal: true
  },
  {
    id: 9,
    slug: "hotel-humboldt",
    name: "Hotel Humboldt",
    description: "Una joya arquitectónica suspendida a 2,140 metros sobre el nivel del mar en la cima del cerro El Ávila. Lujo histórico en las nubes.",
    address: "Cima del Parque Nacional El Ávila, Caracas",
    phone: "+58 212 9090111",
    whatsapp: "+58 424 9990000",
    website: "https://hotelhumboldtve.com",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Caracas",
    destination_slug: "caracas",
    primary_image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop",
    rating_avg: 4.8,
    review_count: 88,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"restaurante\", \"piscina\", \"spa\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 10,
    slug: "lidotel-barquisimeto",
    name: "Lidotel Barquisimeto",
    description: "Estilo, elegancia y excelente atención boutique en el centro occidente del país. Conectado directamente al C.C. Sambil Barquisimeto.",
    address: "Avenida Venezuela con Bracamonte, Barquisimeto, Lara",
    phone: "+58 251 2501111",
    whatsapp: "+58 412 3334455",
    website: "https://www.lidotel.com.ve",
    category_name: "Hoteles",
    category_slug: "hoteles",
    destination_name: "Barquisimeto",
    destination_slug: "barquisimeto",
    primary_image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&auto=format&fit=crop",
    rating_avg: 4.5,
    review_count: 220,
    price_level: "$$$",
    is_featured: false,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\"]",
    membership_tier: "plata",
    has_hdv_seal: false
  },

  // POSADAS
  {
    id: 2,
    slug: "posada-la-cigala",
    name: "Posada La Cigala",
    description: "Hermosa posada boutique en el Gran Roque, atendida por sus propios dueños. Excelente gastronomía caribeña y excursiones privadas a los cayos.",
    address: "Calle La Iglesia, Gran Roque, Los Roques",
    phone: "+58 212 9771234",
    whatsapp: "+58 424 9876543",
    website: "https://lacigala.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Los Roques",
    destination_slug: "los-roques",
    primary_image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
    rating_avg: 4.9,
    review_count: 187,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"restaurante\", \"jardin\", \"spa\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 4,
    slug: "campamento-canaima",
    name: "Campamento Canaima",
    description: "Ubicado a orillas de la laguna de Canaima, con vistas espectaculares a los saltos Hacha, Golondrina y Wadaima. Habitaciones premium ecológicas.",
    address: "Laguna de Canaima, Parque Nacional Canaima, Bolívar",
    phone: "+58 286 9621234",
    whatsapp: "+58 414 8889900",
    website: "https://campamentocanaima.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Canaima",
    destination_slug: "canaima",
    primary_image: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=800&auto=format&fit=crop",
    rating_avg: 4.9,
    review_count: 234,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"restaurante\", \"jardin\"]",
    membership_tier: "oro",
    has_hdv_seal: true
  },
  {
    id: 5,
    slug: "posada-mediterraneo",
    name: "Posada Mediterráneo",
    description: "Un rincón de relajación en Los Roques con diseño de influencia mediterránea, aire acondicionado, excursiones guiadas y cocina fusión gourmet diaria.",
    address: "Avenida Principal, Gran Roque, Los Roques",
    phone: "+58 412 1112233",
    whatsapp: "+58 412 1112233",
    website: "https://posadamediterraneo.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Los Roques",
    destination_slug: "los-roques",
    primary_image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop",
    rating_avg: 4.7,
    review_count: 98,
    price_level: "$$$",
    is_featured: false,
    services: "[\"wifi\", \"restaurante\", \"spa\"]",
    membership_tier: "plata",
    has_hdv_seal: false
  },
  {
    id: 11,
    slug: "posada-la-ardilena",
    name: "Posada La Ardileña",
    description: "Exclusiva posada construida sobre palafitos en el Parque Nacional Morrocoy, con muelle privado y paseos en lancha rápida incluidos.",
    address: "Sector Agua Salobre, Parque Nacional Morrocoy, Falcón",
    phone: "+58 424 2734537",
    whatsapp: "+58 424 2734537",
    website: "https://laardilena.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Morrocoy",
    destination_slug: "morrocoy",
    primary_image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop",
    rating_avg: 4.8,
    review_count: 112,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"piscina\", \"restaurante\", \"estacionamiento\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 12,
    slug: "posada-los-cocos",
    name: "Posada Los Cocos",
    description: "Un oasis tropical en Tucacas. Lindas cabañas rodeadas de cocoteros y piscina, con atención personalizada y traslados privados a los cayos.",
    address: "Sector Puerto Flechado, Tucacas, Falcón",
    phone: "+58 424 4413782",
    whatsapp: "+58 424 4413782",
    website: "https://posadaloscocos.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Morrocoy",
    destination_slug: "morrocoy",
    primary_image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
    rating_avg: 4.8,
    review_count: 76,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"piscina\", \"restaurante\", \"estacionamiento\", \"jardin\"]",
    membership_tier: "oro",
    has_hdv_seal: true
  },
  {
    id: 13,
    slug: "posada-alto-viento",
    name: "Posada Alto Viento",
    description: "Confortable posada andina en las lomas de Cubiro. Hermosas vistas panorámicas del valle, clima frío de montaña y chimenea.",
    address: "Lomas de Cubiro, Cubiro, Lara",
    phone: "+58 414 5737214",
    whatsapp: "+58 414 5737214",
    website: "https://posadaaltoviento.com",
    category_name: "Posadas",
    category_slug: "posadas",
    destination_name: "Mérida",
    destination_slug: "merida",
    primary_image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop",
    rating_avg: 4.6,
    review_count: 53,
    price_level: "$$",
    is_featured: false,
    services: "[\"wifi\", \"estacionamiento\", \"restaurante\", \"jardin\"]",
    membership_tier: "plata",
    has_hdv_seal: false
  },

  // COMPLEJOS
  {
    id: 14,
    slug: "lidotel-paraguana",
    name: "Lidotel Boutique Paraguaná",
    description: "Complejo vacacional de lujo conectado al C.C. Sambil Paraguaná. Cuenta con amplias habitaciones, piscina de diseño y centro de negocios.",
    address: "Avenida Leonardo Da Vinci, Punto Fijo, Falcón",
    phone: "+58 269 4101111",
    whatsapp: "+58 424 4922757",
    website: "https://lidotel.com.ve",
    category_name: "Complejos",
    category_slug: "complejos",
    destination_name: "Morrocoy",
    destination_slug: "morrocoy",
    primary_image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop",
    rating_avg: 4.6,
    review_count: 120,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\"]",
    membership_tier: "oro",
    has_hdv_seal: true
  },
  {
    id: 15,
    slug: "marriott-maracay",
    name: "Marriott Maracay Golf Resort",
    description: "Un imponente complejo hotelero de diseño histórico rodeado de naturaleza. Ofrece campo de golf de 18 hoyos, piscina olímpica y spa.",
    address: "Avenida Las Delicias, Maracay, Aragua",
    phone: "+58 243 2652111",
    whatsapp: "+58 412 2070894",
    website: "https://marriott.com",
    category_name: "Complejos",
    category_slug: "complejos",
    destination_name: "Mérida",
    destination_slug: "merida",
    primary_image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&auto=format&fit=crop",
    rating_avg: 4.5,
    review_count: 310,
    price_level: "$$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\", \"gimnasio\", \"spa\"]",
    membership_tier: "diamante",
    has_hdv_seal: true
  },
  {
    id: 16,
    slug: "punta-palma",
    name: "Punta Palma Hotel & Marina",
    description: "Complejo residencial y náutico sobre las colinas del Cerro El Morro. Marina privada, playa exclusiva y asombrosas vistas al mar Caribe.",
    address: "Cerro El Morro, Lechería, Anzoátegui",
    phone: "+58 281 2811211",
    whatsapp: "+58 424 8352530",
    website: "https://puntapalma.com",
    category_name: "Complejos",
    category_slug: "complejos",
    destination_name: "Puerto La Cruz",
    destination_slug: "puerto-la-cruz",
    primary_image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop",
    rating_avg: 4.4,
    review_count: 95,
    price_level: "$$$",
    is_featured: false,
    services: "[\"wifi\", \"estacionamiento\", \"piscina\", \"restaurante\"]",
    membership_tier: "plata",
    has_hdv_seal: false
  },

  // OTROS (RESTAURANTE)
  {
    id: 6,
    slug: "restaurante-alto-gastronomia",
    name: "Restaurante Alto",
    description: "Considerado uno de los mejores restaurantes del país, liderado por chefs de renombre que reinventan la cocina tradicional venezolana con toques contemporáneos.",
    address: "1ra Avenida de Los Palos Grandes, Caracas",
    phone: "+58 212 2843655",
    whatsapp: "+58 416 1234599",
    website: "http://altorestaurante.com",
    category_name: "Restaurantes",
    category_slug: "restaurantes",
    destination_name: "Caracas",
    destination_slug: "caracas",
    primary_image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop",
    rating_avg: 4.7,
    review_count: 456,
    price_level: "$$$",
    is_featured: true,
    services: "[\"wifi\", \"estacionamiento\", \"restaurante\"]",
    membership_tier: "oro",
    has_hdv_seal: false
  }
];
